/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_zqf_jniseries_JNIImpl */

#ifndef _Included_com_zqf_jniseries_JNIImpl
#define _Included_com_zqf_jniseries_JNIImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zqf_jniseries_JNIImpl
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zqf_jniseries_JNIImpl_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
